project1/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project1/recipes/urls.py
from django.urls import path
from recipes import views

# recipes:home
app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),  # Home page
    path('recipes/search/', views.search, name='search'),  # Search page
    path('recipes/category/<int:category_id>/', views.category, name='category'),  # Category page
    path('recipes/<int:id>/', views.recipe, name='recipe'),  # Recipe page
]

project1/recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=60)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=60)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to="recipes/covers/%Y/%m/%d/", blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

project1/recipes/views.py
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from recipes.models import Recipe


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by("-id")
    context = {"title": "Home | Recipes", "recipes": recipes}
    return render(request, "recipes/pages/home.html", context)


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(category__id=category_id, is_published=True).order_by(
            "-id"
        )
    )
    context = {
        "title": f"{recipes[0].category.name} - Category | Recipes",
        "recipes": recipes,
    }

    return render(request, "recipes/pages/home.html", context)


def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)
    context = {
        "title": f"{recipe.title} | Recipes",
        "recipe": recipe,
        "is_detail": True,
    }
    return render(request, "recipes/pages/recipe-detail.html", context)


def search(request):
    search_query = request.GET.get("q")

    if not search_query:
        raise Http404("No query provided")

    return render(request, "recipes/pages/search.html", {"title": "Search | Recipes"})

project1/recipes/templates/recipes/pages/home.html
{% extends "global/base.html" %}
{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include "recipes/partials/recipe.html" %}
    {% empty %}
        <h1>No recipes found</h1>
    {% endfor %}
</div>
{% endblock content %}

project1/recipes/templates/recipes/pages/recipe-detail.html
{% extends "global/base.html" %}
{% block content %}
<div class="main-content main-content-detail container">
    {% include "recipes/partials/recipe.html" %}
</div>
{% endblock content %}

project1/recipes/templates/recipes/pages/search.html
{% extends "global/base.html" %}
{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include "recipes/partials/recipe.html" %}
    {% empty %}
        <h1>No recipes found</h1>
    {% endfor %}
</div>
{% endblock content %}

project1/recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Letícia Fernandes</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

project1/recipes/templates/recipes/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css"
        integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css"
        integrity="sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/solid.min.css"
        integrity="sha512-pZlKGs7nEqF4zoG0egeK167l6yovsuL8ap30d07kA5AJUq+WysFlQ02DLXAmN3n0+H3JVz5ni8SJZnrOaYXWBA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "recipes/css/styles.css" %}">
    <title>{{title}}</title>
</head>

project1/recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa-solid fa-utensils"></i><span>Recipes</span>
            </a>
        </h1>
    </div>
</header>

project1/recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src={{recipe.cover.url}} alt="">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{recipe.title}}
            </a>
        </h2>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author is not None %}
                {% if recipe.author.first_name %}
                    {{recipe.author.first_name}} {{recipe.author.last_name}}
                {% else %}
                    {{recipe.author.username}}
                {% endif %}
            {% else %}
                unknown
            {% endif %}
            </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at}}
        </span>
        {% if  recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Prep Time</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Servings</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>see more...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html %}
                {{recipe.preparation_steps|safe}}
            {% else %}
                {{recipe.preparation_steps|linebreaksbr}}
            {% endif %}
        </div>
    {% endif %}
</div>

project1/recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'recipes:search' %}" method="GET" class="search-form">
            <input type="search" placeholder="Search for recipes" class="search-input" name="q" required>
            <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
        </form>
    </div>
</div>